---
- block:
    - name: Peform an APT update & upgrade
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install some needed packages
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - git
        - vim
        - zsh
